config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  resources :products, :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def cart_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    return sum
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true

  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def order_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    return sum
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :line_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :current_cart

  private

  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id].nil?
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :address, :contact, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :address, :contact, :password, :current_password])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path, notice: 'Cart Emptied!'
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :find_line_item, except: [:create]

  def create
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart
    if current_cart.products.include?(chosen_product)
      @line_item = current_cart.line_items.find_by(product_id: chosen_product)
      @line_item.quantity += 1
    else
      @line_item = LineItem.new(quantity: 1, product: chosen_product)
      current_cart.line_items << @line_item
    end
    @line_item.order = @order
    @cart = current_cart
    redirect_to products_path, alert: "#{@line_item.product.product_name} added in cart"
  end

  def destroy
    @line_item.destroy
    redirect_to cart_path(@current_cart), alert: "#{@line_item.product.product_name} removed from cart."
  end

  def add_quantity
    @line_item.quantity += 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @line_item.quantity -= 1 if @line_item.quantity > 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  private

  def find_line_item
    @line_item = LineItem.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path, alert: 'Order placed successfully :)'
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to products_path, alert: 'Order Cancelled!', status: :see_other
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :contact, :payment_mode)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, except: [:index, :show, :new, :create]

  def index
    @products = Product.all
  end

  # no specific product displayed, root path displays all products
  def show
    redirect_to root_path
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save!
      redirect_to root_path, alert: "New Product '#{@product.product_name}' added."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, alert: 'Product Updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :description,:image, :price)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h2> Your Shopping Cart </h2>
<button><%= link_to "Back to Products", root_path %></br></button>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <ul>
      <li>
        <p><h4>Item: <%= line_item.product.product_name %></h4> Price: <%= line_item.product.price %> | Quantity: <%= line_item.quantity %> </br>  Total Price: <%= line_item.total_price %></p>
        
            <button><%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %></button>
            <button><%= link_to "Remove one", line_item_reduce_path(:id => line_item), method: :post %></button>
            <button><%= link_to "Remove from cart", line_item_path(line_item), method: :delete %></button>
      </li>
    </ul>  
  <% end %>
</ul>
</br>
<h3>Total Cart Amount: Rs. <%= @cart.cart_total%></h3>
<button><%= link_to "Checkout", new_order_path %></br></button>
<button><%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}%></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :contact %><br/>
    <%= f.text_field :contact, autofocus: true %>
  <p>
  <p>
    <%= f.label :payment_mode %><br>
    <%= f.text_field :payment_mode %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/orders/index.html.erb
<h2>Your Orders</h2>
<ul>
  <% @orders.each do |order| %>
      <li>
        Order Date&Time: <%= link_to order.created_at, order %>
      </li>
      </br>
  <% end %>
</ul>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render "form", order: @order %>

app/views/orders/show.html.erb
<h3>Order Details: </h3>

<h4>Delivery Info</h4>
<p>Name: <%= @order.name %></p>
<p>Email: <%= @order.email %></p>
<p>Contact: <%= @order.contact %></p>
<p>Mode of Payment: <%= @order.payment_mode %></p>
<p>Address for delivery: <%= @order.address %></p>
</br>

<h4>Order Info</h4>
<ul>
	<% @order.line_items.each do |item| %>
		<li><%= item.quantity %> x <%= item.product.product_name %> = Rs. <%= item.total_price%></li>
	<% end %>
	<h4>Total Order Amount: Rs. <%=@order.order_total %></h4>
</ul>
</br>
<button><%= link_to "Cancel Order", order_path(@order),method: :delete, data: {confirm: "Are you sure?"}%></button>

app/views/products/_form.html.erb
<%= form_with model: product do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :product_name, required: true, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description, required: true %>
  </p>

  <p>
  <%= f.label :image %><br>
  <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, step: :any, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Shopping Application</h1></br>

  <% if user_signed_in? %>
    <%= link_to "Edit Profile", edit_user_registration_path %>
    <button class="sign_out"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></button></br></br>

    <h5> Hi, <%= current_user.name%></h5>
    <h6> Welcome to our Shopping Application! Browse and add products of your choice to the cart :)</h6>
    <button class="view_order"><%= link_to "View Your Orders", orders_path %></button>
    <button ><%= link_to "Go to Cart", cart_path(@current_cart) %></button></br></br>
    </p>
    <p>
    <h3>Available Products:</h3>
    <button><%= link_to "Add New Product", new_product_path %></button></br></br>
    <ul>
        <% @products.each do |product| %>
            <h4><%= product.product_name%></h4>
            <p><%= product.description%></p>


            <div class="image"><%= image_tag(product.image.url, alt: 'Image') if product.image? %></div>

            <h4>Price: Rs.<%= product.price%></h4>
            <p>
            <%= link_to "Edit", edit_product_path(product) %> |
            <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
            <%= button_to "Add #{product.product_name} to cart", line_items_path(:product_id => product.id) %>
            </p>
            </br>
          <% end %>
    </ul>

  <% else %>
    <%= link_to 'Sign In', new_user_session_path %></br>
    <%= link_to 'Sign Up', new_user_registration_path %></br>
  <% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>